/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Contract {
  'id' : bigint,
  'status' : string,
  'name' : string,
  'createdAt' : bigint,
  'alreadyExpended' : [] | [bigint],
  'sections' : Array<SectionEntry>,
  'contractValue' : [] | [bigint],
}
export interface ContractResponse {
  'id' : bigint,
  'status' : string,
  'name' : string,
  'createdAt' : bigint,
  'alreadyExpended' : [] | [bigint],
  'contractValue' : [] | [bigint],
}
export type ExternalBlob = Uint8Array;
export interface FileRef {
  'blob' : ExternalBlob,
  'fileType' : string,
  'filename' : string,
  'fileId' : string,
  'uploadedAt' : bigint,
}
export interface SectionEntry {
  'files' : Array<FileRef>,
  'sectionType' : SectionType,
  'notes' : string,
}
export type SectionType = { 'LOI' : null } |
  { 'TenderDetails' : null } |
  { 'SiteExpenses' : null } |
  { 'RunningBill' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addFileToSection' : ActorMethod<
    [bigint, SectionType, string, ExternalBlob, string, string],
    undefined
  >,
  'createContract' : ActorMethod<
    [string, string, [] | [bigint], [] | [bigint]],
    bigint
  >,
  'deleteContract' : ActorMethod<[bigint], undefined>,
  'getAllContracts' : ActorMethod<[], Array<ContractResponse>>,
  'getContract' : ActorMethod<[bigint], ContractResponse>,
  'getContractFileCounts' : ActorMethod<[bigint], Array<[string, bigint]>>,
  'getManualEntry' : ActorMethod<
    [bigint, SectionType],
    [] | [{ 'rows' : Array<Array<string>>, 'headers' : Array<string> }]
  >,
  'getSectionFiles' : ActorMethod<
    [bigint, SectionType],
    { 'files' : Array<FileRef>, 'notes' : string }
  >,
  'queryContractsCompatible' : ActorMethod<[], Array<Contract>>,
  'removeFileFromSection' : ActorMethod<
    [bigint, SectionType, string],
    undefined
  >,
  'saveManualEntry' : ActorMethod<
    [bigint, SectionType, Array<string>, Array<Array<string>>],
    undefined
  >,
  'seedWithContracts' : ActorMethod<[bigint], undefined>,
  'updateContract' : ActorMethod<
    [bigint, string, string, [] | [bigint], [] | [bigint]],
    undefined
  >,
  'updateSectionNotes' : ActorMethod<[bigint, SectionType, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];