/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const SectionType = IDL.Variant({
  'LOI' : IDL.Null,
  'MaterialExpenses' : IDL.Null,
  'TenderDetails' : IDL.Null,
  'SiteExpenses' : IDL.Null,
  'RunningBill' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ContractResponse = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'alreadyExpended' : IDL.Opt(IDL.Nat),
  'contractValue' : IDL.Opt(IDL.Nat),
});
export const FileRef = IDL.Record({
  'blob' : ExternalBlob,
  'fileType' : IDL.Text,
  'filename' : IDL.Text,
  'fileId' : IDL.Text,
  'uploadedAt' : IDL.Int,
});
export const SectionEntry = IDL.Record({
  'files' : IDL.Vec(FileRef),
  'sectionType' : SectionType,
  'notes' : IDL.Text,
});
export const Contract = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'alreadyExpended' : IDL.Opt(IDL.Nat),
  'sections' : IDL.Vec(SectionEntry),
  'contractValue' : IDL.Opt(IDL.Nat),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addFileToSection' : IDL.Func(
      [IDL.Nat, SectionType, IDL.Text, ExternalBlob, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'createContract' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Nat],
      [],
    ),
  'deleteContract' : IDL.Func([IDL.Nat], [], []),
  'getAllContracts' : IDL.Func([], [IDL.Vec(ContractResponse)], ['query']),
  'getContract' : IDL.Func([IDL.Nat], [ContractResponse], ['query']),
  'getContractFileCounts' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getManualEntry' : IDL.Func(
      [IDL.Nat, SectionType],
      [
        IDL.Opt(
          IDL.Record({
            'rows' : IDL.Vec(IDL.Vec(IDL.Text)),
            'headers' : IDL.Vec(IDL.Text),
          })
        ),
      ],
      ['query'],
    ),
  'getSectionFiles' : IDL.Func(
      [IDL.Nat, SectionType],
      [IDL.Record({ 'files' : IDL.Vec(FileRef), 'notes' : IDL.Text })],
      ['query'],
    ),
  'queryContractsCompatible' : IDL.Func([], [IDL.Vec(Contract)], ['query']),
  'removeFileFromSection' : IDL.Func([IDL.Nat, SectionType, IDL.Text], [], []),
  'saveManualEntry' : IDL.Func(
      [IDL.Nat, SectionType, IDL.Vec(IDL.Text), IDL.Vec(IDL.Vec(IDL.Text))],
      [],
      [],
    ),
  'seedWithContracts' : IDL.Func([IDL.Nat], [], []),
  'updateContract' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [],
      [],
    ),
  'updateSectionNotes' : IDL.Func([IDL.Nat, SectionType, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const SectionType = IDL.Variant({
    'LOI' : IDL.Null,
    'MaterialExpenses' : IDL.Null,
    'TenderDetails' : IDL.Null,
    'SiteExpenses' : IDL.Null,
    'RunningBill' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ContractResponse = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'alreadyExpended' : IDL.Opt(IDL.Nat),
    'contractValue' : IDL.Opt(IDL.Nat),
  });
  const FileRef = IDL.Record({
    'blob' : ExternalBlob,
    'fileType' : IDL.Text,
    'filename' : IDL.Text,
    'fileId' : IDL.Text,
    'uploadedAt' : IDL.Int,
  });
  const SectionEntry = IDL.Record({
    'files' : IDL.Vec(FileRef),
    'sectionType' : SectionType,
    'notes' : IDL.Text,
  });
  const Contract = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'alreadyExpended' : IDL.Opt(IDL.Nat),
    'sections' : IDL.Vec(SectionEntry),
    'contractValue' : IDL.Opt(IDL.Nat),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addFileToSection' : IDL.Func(
        [IDL.Nat, SectionType, IDL.Text, ExternalBlob, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'createContract' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Nat],
        [],
      ),
    'deleteContract' : IDL.Func([IDL.Nat], [], []),
    'getAllContracts' : IDL.Func([], [IDL.Vec(ContractResponse)], ['query']),
    'getContract' : IDL.Func([IDL.Nat], [ContractResponse], ['query']),
    'getContractFileCounts' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getManualEntry' : IDL.Func(
        [IDL.Nat, SectionType],
        [
          IDL.Opt(
            IDL.Record({
              'rows' : IDL.Vec(IDL.Vec(IDL.Text)),
              'headers' : IDL.Vec(IDL.Text),
            })
          ),
        ],
        ['query'],
      ),
    'getSectionFiles' : IDL.Func(
        [IDL.Nat, SectionType],
        [IDL.Record({ 'files' : IDL.Vec(FileRef), 'notes' : IDL.Text })],
        ['query'],
      ),
    'queryContractsCompatible' : IDL.Func([], [IDL.Vec(Contract)], ['query']),
    'removeFileFromSection' : IDL.Func(
        [IDL.Nat, SectionType, IDL.Text],
        [],
        [],
      ),
    'saveManualEntry' : IDL.Func(
        [IDL.Nat, SectionType, IDL.Vec(IDL.Text), IDL.Vec(IDL.Vec(IDL.Text))],
        [],
        [],
      ),
    'seedWithContracts' : IDL.Func([IDL.Nat], [], []),
    'updateContract' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [],
        [],
      ),
    'updateSectionNotes' : IDL.Func([IDL.Nat, SectionType, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };