/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ContractResponse {
    id: bigint;
    status: string;
    name: string;
    createdAt: bigint;
    alreadyExpended?: bigint;
    contractValue?: bigint;
}
export interface SectionEntry {
    files: Array<FileRef>;
    sectionType: SectionType;
    notes: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Contract {
    id: bigint;
    status: string;
    name: string;
    createdAt: bigint;
    alreadyExpended?: bigint;
    sections: Array<SectionEntry>;
    contractValue?: bigint;
}
export interface FileRef {
    blob: ExternalBlob;
    fileType: string;
    filename: string;
    fileId: string;
    uploadedAt: bigint;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum SectionType {
    LOI = "LOI",
    MaterialExpenses = "MaterialExpenses",
    TenderDetails = "TenderDetails",
    SiteExpenses = "SiteExpenses",
    RunningBill = "RunningBill"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    addFileToSection(contractId: bigint, section: SectionType, fileId: string, blob: ExternalBlob, filename: string, fileType: string): Promise<void>;
    createContract(name: string, status: string, contractValue: bigint | null, alreadyExpended: bigint | null): Promise<bigint>;
    deleteContract(id: bigint): Promise<void>;
    getAllContracts(): Promise<Array<ContractResponse>>;
    getContract(id: bigint): Promise<ContractResponse>;
    getContractFileCounts(id: bigint): Promise<Array<[string, bigint]>>;
    getManualEntry(contractId: bigint, section: SectionType): Promise<{
        rows: Array<Array<string>>;
        headers: Array<string>;
    } | null>;
    getSectionFiles(contractId: bigint, section: SectionType): Promise<{
        files: Array<FileRef>;
        notes: string;
    }>;
    queryContractsCompatible(): Promise<Array<Contract>>;
    removeFileFromSection(contractId: bigint, section: SectionType, fileId: string): Promise<void>;
    saveManualEntry(contractId: bigint, section: SectionType, headers: Array<string>, rows: Array<Array<string>>): Promise<void>;
    seedWithContracts(seedCount: bigint): Promise<void>;
    updateContract(id: bigint, name: string, status: string, contractValue: bigint | null, alreadyExpended: bigint | null): Promise<void>;
    updateSectionNotes(contractId: bigint, section: SectionType, notes: string): Promise<void>;
}
import type { Contract as _Contract, ContractResponse as _ContractResponse, ExternalBlob as _ExternalBlob, FileRef as _FileRef, SectionEntry as _SectionEntry, SectionType as _SectionType, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async addFileToSection(arg0: bigint, arg1: SectionType, arg2: string, arg3: ExternalBlob, arg4: string, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addFileToSection(arg0, to_candid_SectionType_n8(this._uploadFile, this._downloadFile, arg1), arg2, await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFileToSection(arg0, to_candid_SectionType_n8(this._uploadFile, this._downloadFile, arg1), arg2, await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
            return result;
        }
    }
    async createContract(arg0: string, arg1: string, arg2: bigint | null, arg3: bigint | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createContract(arg0, arg1, to_candid_opt_n11(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n11(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createContract(arg0, arg1, to_candid_opt_n11(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n11(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async deleteContract(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteContract(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteContract(arg0);
            return result;
        }
    }
    async getAllContracts(): Promise<Array<ContractResponse>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllContracts();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllContracts();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContract(arg0: bigint): Promise<ContractResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.getContract(arg0);
                return from_candid_ContractResponse_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContract(arg0);
            return from_candid_ContractResponse_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContractFileCounts(arg0: bigint): Promise<Array<[string, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContractFileCounts(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContractFileCounts(arg0);
            return result;
        }
    }
    async getManualEntry(arg0: bigint, arg1: SectionType): Promise<{
        rows: Array<Array<string>>;
        headers: Array<string>;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getManualEntry(arg0, to_candid_SectionType_n8(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getManualEntry(arg0, to_candid_SectionType_n8(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSectionFiles(arg0: bigint, arg1: SectionType): Promise<{
        files: Array<FileRef>;
        notes: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getSectionFiles(arg0, to_candid_SectionType_n8(this._uploadFile, this._downloadFile, arg1));
                return from_candid_record_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSectionFiles(arg0, to_candid_SectionType_n8(this._uploadFile, this._downloadFile, arg1));
            return from_candid_record_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async queryContractsCompatible(): Promise<Array<Contract>> {
        if (this.processError) {
            try {
                const result = await this.actor.queryContractsCompatible();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.queryContractsCompatible();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeFileFromSection(arg0: bigint, arg1: SectionType, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFileFromSection(arg0, to_candid_SectionType_n8(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFileFromSection(arg0, to_candid_SectionType_n8(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async saveManualEntry(arg0: bigint, arg1: SectionType, arg2: Array<string>, arg3: Array<Array<string>>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveManualEntry(arg0, to_candid_SectionType_n8(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveManualEntry(arg0, to_candid_SectionType_n8(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return result;
        }
    }
    async seedWithContracts(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedWithContracts(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedWithContracts(arg0);
            return result;
        }
    }
    async updateContract(arg0: bigint, arg1: string, arg2: string, arg3: bigint | null, arg4: bigint | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateContract(arg0, arg1, arg2, to_candid_opt_n11(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n11(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateContract(arg0, arg1, arg2, to_candid_opt_n11(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n11(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async updateSectionNotes(arg0: bigint, arg1: SectionType, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSectionNotes(arg0, to_candid_SectionType_n8(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSectionNotes(arg0, to_candid_SectionType_n8(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
}
function from_candid_ContractResponse_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContractResponse): ContractResponse {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
async function from_candid_Contract_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Contract): Promise<Contract> {
    return await from_candid_record_n23(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_FileRef_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FileRef): Promise<FileRef> {
    return await from_candid_record_n19(_uploadFile, _downloadFile, value);
}
async function from_candid_SectionEntry_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SectionEntry): Promise<SectionEntry> {
    return await from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_SectionType_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SectionType): SectionType {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        rows: Array<Array<string>>;
        headers: Array<string>;
    }]): {
    rows: Array<Array<string>>;
    headers: Array<string>;
} | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: string;
    name: string;
    createdAt: bigint;
    alreadyExpended: [] | [bigint];
    contractValue: [] | [bigint];
}): {
    id: bigint;
    status: string;
    name: string;
    createdAt: bigint;
    alreadyExpended?: bigint;
    contractValue?: bigint;
} {
    return {
        id: value.id,
        status: value.status,
        name: value.name,
        createdAt: value.createdAt,
        alreadyExpended: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.alreadyExpended)),
        contractValue: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.contractValue))
    };
}
async function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    files: Array<_FileRef>;
    notes: string;
}): Promise<{
    files: Array<FileRef>;
    notes: string;
}> {
    return {
        files: await from_candid_vec_n17(_uploadFile, _downloadFile, value.files),
        notes: value.notes
    };
}
async function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    blob: _ExternalBlob;
    fileType: string;
    filename: string;
    fileId: string;
    uploadedAt: bigint;
}): Promise<{
    blob: ExternalBlob;
    fileType: string;
    filename: string;
    fileId: string;
    uploadedAt: bigint;
}> {
    return {
        blob: await from_candid_ExternalBlob_n20(_uploadFile, _downloadFile, value.blob),
        fileType: value.fileType,
        filename: value.filename,
        fileId: value.fileId,
        uploadedAt: value.uploadedAt
    };
}
async function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: string;
    name: string;
    createdAt: bigint;
    alreadyExpended: [] | [bigint];
    sections: Array<_SectionEntry>;
    contractValue: [] | [bigint];
}): Promise<{
    id: bigint;
    status: string;
    name: string;
    createdAt: bigint;
    alreadyExpended?: bigint;
    sections: Array<SectionEntry>;
    contractValue?: bigint;
}> {
    return {
        id: value.id,
        status: value.status,
        name: value.name,
        createdAt: value.createdAt,
        alreadyExpended: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.alreadyExpended)),
        sections: await from_candid_vec_n24(_uploadFile, _downloadFile, value.sections),
        contractValue: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.contractValue))
    };
}
async function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    files: Array<_FileRef>;
    sectionType: _SectionType;
    notes: string;
}): Promise<{
    files: Array<FileRef>;
    sectionType: SectionType;
    notes: string;
}> {
    return {
        files: await from_candid_vec_n17(_uploadFile, _downloadFile, value.files),
        sectionType: from_candid_SectionType_n27(_uploadFile, _downloadFile, value.sectionType),
        notes: value.notes
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    LOI: null;
} | {
    MaterialExpenses: null;
} | {
    TenderDetails: null;
} | {
    SiteExpenses: null;
} | {
    RunningBill: null;
}): SectionType {
    return "LOI" in value ? SectionType.LOI : "MaterialExpenses" in value ? SectionType.MaterialExpenses : "TenderDetails" in value ? SectionType.TenderDetails : "SiteExpenses" in value ? SectionType.SiteExpenses : "RunningBill" in value ? SectionType.RunningBill : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ContractResponse>): Array<ContractResponse> {
    return value.map((x)=>from_candid_ContractResponse_n13(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FileRef>): Promise<Array<FileRef>> {
    return await Promise.all(value.map(async (x)=>await from_candid_FileRef_n18(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Contract>): Promise<Array<Contract>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Contract_n22(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SectionEntry>): Promise<Array<SectionEntry>> {
    return await Promise.all(value.map(async (x)=>await from_candid_SectionEntry_n25(_uploadFile, _downloadFile, x)));
}
async function to_candid_ExternalBlob_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_SectionType_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SectionType): _SectionType {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SectionType): {
    LOI: null;
} | {
    MaterialExpenses: null;
} | {
    TenderDetails: null;
} | {
    SiteExpenses: null;
} | {
    RunningBill: null;
} {
    return value == SectionType.LOI ? {
        LOI: null
    } : value == SectionType.MaterialExpenses ? {
        MaterialExpenses: null
    } : value == SectionType.TenderDetails ? {
        TenderDetails: null
    } : value == SectionType.SiteExpenses ? {
        SiteExpenses: null
    } : value == SectionType.RunningBill ? {
        RunningBill: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
